### PR TITLE
Snail climb algorithm improvements

### PR DESCRIPTION
**Pull request by pncsoares**
The code was broking because of this instruction: `step += climbStepsPerDay`
It cannot be in the 3rd for loop statement because there, this code is executed at the end of a iteration and it must be executed at the beginning of the iteration.
@ma-oliveiramarques

### CODE REVIEW

**Comment by pncsoares** [comment]
Screenshot 2022-03-07 at 13 12 26

**Review by ma-oliveiramarques — APPROVED** [review]
Everything right with the changes, but remember that at this point of the sololearn lessons, the return statement it was not introduced.

**Comment by pncsoares** [comment]
> Everything right with the changes, but remember that at this point of the sololearn lessons, the return statement it was not introduced.

That's correct 😊
Do you want to just stick with what we've learned so far? And as you learn, will we improve the code?

**Comment by ma-oliveiramarques** [comment]
No, in this case it's ok. Yesterday I got the return statement and I understood why you used it, even though I thought it was just for calculations :)

**Pull request merged**
